### PR TITLE
Feature/personal profile

### PR DESCRIPTION
**Pull request by winkidney**
Add profile card to pins4user and boards2user page so that we can have a simple view on user and guided to another page of this user.

image

### CODE REVIEW

**Comment by winkidney** [comment]
@lapo-luchini @overshard I don't know whether we should have some information on personal profile except pins and boards.
I just add some simple "meaningless information" on profile card.

Any idea?

I'd like to merge this PR first and changes may be applied after we have some better ideas, haha.

**Comment by winkidney** [comment]
Have a view here: https://pin.37soloist.com/boards/users/winkidney

**Comment by overshard** [comment]
@winkidney I think personal profile w/ name, email, website, general location (city/country?) is fine as long as they are all optional. Some people might like that data being public and some will not.

**Comment by winkidney** [comment]
@overshard I agree with you.
For most people, they don't want to show their profile to others 💥 
In my opinion, this profile is used to guide us to a pinry-user's boards and pins. 
I wonder how can we use these information to provide better user-experience.

**Pull request merged**
