### PR TITLE
close #161 Add tag auto-complete

### LINKED ISSUE #161: Add tag auto-completion

### PR DESCRIPTION
**Pull request by winkidney**
tag-auto-complete

### CODE REVIEW

**Comment by winkidney** [comment]
@overshard @lapo-luchini Maybe an online demo may help us to review Frontend features because writing E2E tests is really not an easy job.
And, I switched the project's CI system to github workflow and it seems working well.

**Comment by lapo-luchini** [comment]
This feature is SO COOL!

Yes, we can probably arrange a copy on my server that respond to some "wakeup call" from GitHub and fetches new source, migrates DB, and restarts.

**Comment by winkidney** [comment]
I've deployed it on my own server and it seems working well. I will merge this PR first and rollback if something go wrong.

@lapo-luchini It's very nice if you'd like to deploy the latest version on your server and make it automatic-update.
The auto-deploy may be processed after the docker-auto-build fixed (in case that we need almost no work for auto-update demo), what do you think about it?

**Comment by overshard** [comment]
Extremely cool feature!

**Pull request merged**
