### PR TITLE
Feature(WIP): Add board support for Pinry

### PR DESCRIPTION
**Pull request by winkidney**
I'm currently working on new UI by vue.js with webpack workflow because I found it hard to rebuild UI while using old styles.
The old server-render UI will be removed after new UI worked.

- [x] Backend support for board
+ Show:
  - [x] UI: show pins
  - [x] UI: show pins by tag
  - [x] UI: show pins by user
  - [x] UI: Single pin preview
  - [x] UI: show pins by board
  - [x] UI: show boards by user
  - [x] UI: view single pin
+ create/update
  - [x] UI: Pin Edit
    - [x] Create pin from uploaded image
    - [x] Create pin from image url
    - [x] Add a pin to a specified board while creating
    - [x] Delete a pin
    - [x] edit a pin
  - [x] UI: Works with Bookmarklet
  - [x] UI: Create board
  - [x] UI: Delete board
  - [x] UI: Edit board name
  - [x] UI: Add pin to specified board (from pin itself)
  - [x] UI: Remove pin from board
  - [x] UI: Add to board while adding a pin.
+ other
  - [x] UI: user login
  - [x] UI: logout
  - [x] UI: register

All basic features have  done!
More jobs required are listed below:

+ For end users
  + [ ] docker autobuild
  + [ ] automatic config for new-installation
+ CI
  + [x] frontend auto-build in docker
  + [x] migration files for new model
  + [x] nginx config
+ Dev
  + [ ] 404 page?
  + [ ] 403 handler?
  + [x] Remove old codes
  + [x] bookmarklet remote test
  + [x] Browser Extension Link and Test(it works well).
+ Doc
  + [ ] Dev how to 
  + [ ] User's how to and upgrade guide

### CODE REVIEW

**Comment by willstott101** [comment]
Would you be interested in me continuing this PR?

In #103 @overshard seemed interested in moving towards server-side rendering. This PR has introduced a new Vue dependency and IDK which direction is best for this project.

Pinry is a collaborative platform so pins being added via websocket events could provide a really nice UX - suggesting a beefier client built on something like Vue, as opposed to jQuery and Intercooler. However the simplicity of server-rendered Django applications always appeals to me.

**Comment by overshard** [comment]
With Vue we can use "Nuxtjs" to provide server side rendering still. I think something like this is a good direction to go in and will help provide a lot of features quicker that people request. I'm also not sure how much Server Side rendering matters on an "image board" so #103 may no longer be relevant to what we are trying to do anyways.

I think the future of development on Pinry should be a SPA framework and django-rest-frameworks API. There are many solutions to SSR on all popular SPAs now if we need that later.

**Comment by winkidney** [comment]
@overshard Yes SPA makes it easier for us to add new features.

After some sort of searching on Github and Google, I haven't found proper existed solution for our Pin-board, as a result , I have to do it by my own hand.

It's a little complex for me to finish all of the function with vue (without operating DOM directly),  life-cycle in Vue is not always works as I expected(especially re-ordering after new-pins-loading), so I'm working on it at low speed. 

Maybe client-side rendering is enough now, haha.

I will continue to do the work on this pull-request if I have free time.

**Comment by overshard** [comment]
I think client side rendering is perfectly acceptable right now for this project.

**Comment by winkidney** [comment]
@willstott101 PR is very welcome here. You could continue with this PR at any point. You could start a new PR from master branch (I think it's better).
I have no concern on using SSR or client-side-rendering.

If SSR  is easy to build for you and easy to understand for us, you could fork this PR and continuing with the features.

Would you please give me a simple example or reference for the tech-stack you want to use?

**Comment by willstott101** [comment]
I think it would probably be best to continue on using client-side Vue and a Django API. Then we can explore SSR at a later date, once the client-side rendering is in-place.

I'd be tempted to first look at a smaller PR which maybe replaces the upload form with one built in Vue. Then this Boards PR can be more focused on just adding boards, rather than having to also introduce Vue.

Does that make sense?

**Comment by winkidney** [comment]
@willstott101 Make sense for me. This PR could be separate to backend-only feature. You could start from replacing frontend-UI with Vue maybe : ) (or anyway you like).

**Comment by winkidney** [comment]
Some preview:
image
image

**Comment by winkidney** [comment]
Pin board list preview:
image

**Comment by overshard** [comment]
This is looking excellent! I'm going to try and install it this weekend and give it a spin.

**Comment by winkidney** [comment]
@overshard Most of read-only feature works fine and create/update feature is in progress. I'll appreciate that if you could review it for me!

**Comment by winkidney** [comment]
Preview on pin-creation
image

**Comment by winkidney** [comment]
@lapo-luchini @overshard You may take a look at https://en.eagle.cool/ . this tools is really awesome(tagging, search, mark-on-assets, lightweight on meta data), the only shortage is that it lacks support for file syncing.

**Comment by winkidney** [comment]
New preview on board selection for pin-creation：
image

**Comment by winkidney** [comment]
All feature done!
Now the CI and auto build script will be updated!
Some more UX details  will be improved after  all work done.

**Comment by overshard** [comment]
Very cool! I'm checking this out, I'll see if I can get a server up and running with this going on it as an official public demo.

**Comment by winkidney** [comment]
@overshard hah, please take care that I forget to include the migration files generated in current commits(but not affect the demo server), the production-ready release should wait for migration files.

**Comment by winkidney** [comment]
@overshard I have deployed the new Pinry version on my own site: https://pin.37soloist.com/#/

**Comment by overshard** [comment]
@winkidney I'd say we should go ahead and merge this whenever you are comfortable. I'm about to start making a lot of documentation and docker changes and I'd like this to be in master!

**Comment by overshard** [comment]
I'm going to go ahead and merge this and we can continue dev on master, lots of changes incoming.

**Pull request merged**
