### PR TITLE
simplify docker/compose configuration

### PR DESCRIPTION
**Pull request by dunn**
this is a pretty invasive change so i understand if it's not accepted, but these are changes i made for my own docker-based deployment and they might be more generally useful:

- consolidate and simplify the application Dockerfile 
- make `docker-compose up` work with zero configuration
- create .env with defaults, fetch instance-specific vars from the environment
- don't run django and nginx in the same container

if there is interest i can update the documentation accordingly

### CODE REVIEW

**Comment by winkidney** [comment]
Thanks for your contribution!
I have had a glance at your commits and I have some questions:

+ Dockerfile.autobuild should not be removed since our image-building on DockerHub depends on it
+ docker-compose.yml is just for development and designed for advanced users, it should be treated at `local_settings.py` and should be ignored
+ Test scripts (written with bash) should not be removed (may be fixed)
+ And some other details not listed here.

**Comment by dunn** [comment]
ok, restored the test scripts.

> Dockerfile.autobuild should not be removed since our image-building on DockerHub depends on it

is that because it runs `scripts/build_docker.sh`? I can update the dockerfile that script points at; or maybe it should take an argument, since now there's `docker/nginx/Dockerfile` as well.

> docker-compose.yml is just for development and designed for advanced users, it should be treated at local_settings.py and should be ignored

i disagree, `docker-compose up` should work out of the box, so that it doesn't have to be something only for advanced users.  not ignoring `docker-compose.yaml` is the reason for this entire PR, so if that's not something y'all are interested in then this probably is a non-starter.

**Comment by winkidney** [comment]
Feel sorry for that, I'd prefer to make a bootstrap script to create `docker-compose.yml` from docker-compose.example.yml.

BTW: Move some of settings to Environment Variables is not bad : )

**Comment by dunn** [comment]
> .env will never cover all config options.

why shouldn't it?

**Pull request closed without merging**
