### PR TITLE
create docker image for ARM processors (raspberry pi)

### PR DESCRIPTION
**Pull request by chrisdecker1201**
Hello,

I tried to get Pinry get running on a raspberry pi. So I made some changes. Maybe you can use it.

Greets,
Christian

### CODE REVIEW

**Comment by winkidney** [comment]
Thanks for your contribution and nice to see you!
Would you like to change your base image to apline or any other slim docker image?
We had a specific PR to use AplineLinux as base image to reduce the size of built docker, I don't want to break the work.
ref: https://github.com/pinry/pinry/pull/143

**Comment by winkidney** [comment]
And……dose AplineLinux works on RPi？
If yes, you could just replace the pypi source, It will works well.

**Comment by chrisdecker1201** [comment]
Alpine works in RPi. I'm looking if I can switch to alpine images. 

I think the pypi source is still needed for docker builds on systems with not ARM processors.

**Comment by winkidney** [comment]
> 
> 
> Alpine works in RPi. I'm looking if I can switch to alpine images.
> 
> I think the pypi source is still needed for docker builds on systems with not ARM processors.

Does the pypi source work for other platform (x86, etc)?

**Comment by chrisdecker1201** [comment]
I just built the docker image on my x86 pc. As I understand two sources for pip packages are needed because it'll loke for pip packages build for arm on a arm processor and for x86 packages for a x86 processor.

**Comment by chrisdecker1201** [comment]
At the moment I've no time to solve the apline issues I have. Maybe you can accept this PR and I/someone can look after alpine in another PR?

**Comment by winkidney** [comment]
> I just built the docker image on my x86 pc. As I understand two sources for pip packages are needed because it'll loke for pip packages build for arm on a arm processor and for x86 packages for a x86 processor.

Thanks for your great work again and I may not agree to merge your PR since it only works for ARM processor.

Our docker-autobuild is for platform X86 or X86_64 now and we should not break it. 
Hope you could resolve the platform-issue caused by pypi source.

**Comment by chrisdecker1201** [comment]
Maybe I'm explaining it wrong. The PR will not break you docker-autobuild. When the pip packages will be installed, pipenv will look first in pypi to find a package which fits his needs (x86 on a x86 platform), when there is no matching package it will look in piwheels. So for the x86/x86_64 platform it should be the same, but additionally it will work for ARM too, because when there is no package in pypi he will maybe find one in piwheels.

**Pull request merged**
