### PR TITLE
Feature:  Upgrade django to 1.11 LTS

### PR DESCRIPTION
**Pull request by winkidney**
I have submit a patch to django's master branch to fix the RuntimeError while saving wepb file for djan

But, the patch will not be applied to Django 1.8, as a result I made a patch to upgrade django to 1.11 LTS.

+ Upgrade Django to 1.11 LTS
+ Integrates django-images into this project
+ Use new permission interface instead of auth-backend (the old one has an issue in new version of tastypie that may cause permision error on Image object)
  + Pin-list is public by default
  + Only the pin owner can change its PinResource
+ Upgrade Tastypie to lastest version

Ref: https://www.djangoproject.com/download/#supported-versions

Ref: https://github.com/django/django/pull/10331

### CODE REVIEW

**Comment by winkidney** [comment]
Test on Python3.4 passed, and the usage of new migration framework may cause some problem in module "django-images".

New version of django-images is moved to use django-migration instead of south-migration.

The total fresh install will have no errors.

Upgrade from old version of Pinry needs some workaround, for example, it will cause errors like 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django/core/management/__init__.py", line 364, in execute_fr
om_command_line
    utility.execute()
  File "/home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 86, in han
dle
    executor.loader.check_consistent_history(connection)
  File "/home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django/db/migrations/loader.py", line 298, in check_consiste
nt_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration core.0001_initial is applied before its dependency django_images.000
1_initial on database 'default'.
```

**Comment by overshard** [comment]
django-images probably just needs dropped all-together/built into the project. It hasn't been updated in a while and updating it separately seems silly. We may have to just release as Pinry 2 with a document explaining how to do a more complicated upgrade. I'll see about what can be done with that, it may be just running `python manage.py migrate --fake` would work.

**Comment by winkidney** [comment]
I will try to built django-images into this peoject if I have free time in this PR.

Pinry 2.0 seems awesome!

Your reply is really fast, haha.

**Comment by winkidney** [comment]
Guide to upgrade to lastest version:

At first in the old branch.

```bash
git checkout 1.x-lastest version
pipenv install 
pipenv shell

# Upgrade to lastest version of django-images
pip install -U git+https://github.com/mirumee/django-images.git
python manage.py makemigrations
python manage.py migrate --fake-initial

# clean action
pip uninstall django-images
# It will ask if you want to remove an extra file named like
# Uninstalling django-images-0.4.3:
# -------------------------------------------
#  Would remove:
#    /home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django_images-0.4.3.dist-info/*
#    /home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django_images/*
#  Would not remove (might be manually added):
#    /home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django_images/migrations/0002_auto_20180826_0845.py
# Proceed (y/n)? 
# ------------------------------------------
# Please remove the file it by hand
rm /home/winkidney/.virtualenvs/pinry-DDNksN0m/lib/python3.4/site-packages/django_images/migrations/0002_auto_20180826_0845.py

# exit virtualenv
exit
```
Then checkout to version 2.x 

```bash
git checkout master
make install
make migrate
# Try to run as development server
make serve
# If no error occurs, just enjoy it
```

@overshard Please have a try and give me a review about it, thanks~

**Comment by winkidney** [comment]
Meet some 401 error on API-CALL, working on it~

**Comment by winkidney** [comment]
update: 

+ All pins is public by default

**Comment by overshard** [comment]
I'll try doing this here soon on my instance and see how it goes.

**Comment by winkidney** [comment]
I have  upgrade with this PR, I use my own docker-compose config and docker build option.

I haven't submit a pull request since I don't know if it's necessary to apply the changes to Pinry master ( and, it will also affects pinry-docker project).

Ref: https://pin.winkidney.com/

**Comment by winkidney** [comment]
I'd like to merge this PR if no further comments : )

**Comment by overshard** [comment]
This looks good, it seems to have worked on my system when I tried it earlier!

**Comment by florihupf** [comment]
Hello, 

I have an ages old instance v1.4.2 I need to migrate to latest 2.16.

But no matter what I precisely follow the steps outlined above, I always end up with a "fresh install" even though it tells me all migrations have been applied.

Is there a way to manually dump the entries from the old sqlite file and import them into the new instance?

TIA!

**Comment by winkidney** [comment]
@florihupf Sorry for my missing on this comment, have you ever make it done?
I recommend you to export your data as json and then take it to new instance then run "python manage.py migrate".

If you have any further problem, I may help  you online with other real-time way (for example with RDP or SSH or direct message via tools like Discord)

**Comment by florihupf** [comment]
@winkidney Thanks for the follow up. I managed to hack up a small python script that reads the old SQLite db and appends entries as needed to the new one. 

I was surprised how straightforward that process was and I am all set. 

Thanks again for all the great work and I do love this project. Cheers!

**Pull request merged**
