### PR TITLE
Add watermark function. Modify param name and some comments.

### PR DESCRIPTION
**Pull request by Rousong**
watermark_1
Add watermark function for pinry.
Modify the setting file to enble watermark. The default setting is False.
Change it to True.
You will get a watermarked pin after you upload.
watermark_2

### CODE REVIEW

**Comment by winkidney** [comment]
Thanks for your contribution first.
I will have a detail review once I have time.

I guess most people have no require for this feature since Pinry is mostly a private site for a group of creators.
And, personally I don't agree to add watermark to original image (since it's a break to the image).

Otherwise, we should not integrate `arial.ttf` to this project since its license tells that it's not free to use.

What's your opinion about this featue @overshard @lapo-luchini ?

**Comment by lapo-luchini** [comment]
> What's your opinion about this feature?

I don't have strong opinions about it… on one hand I can see it can be useful to someone, on the other hand I agree keeping the original image intact is a good part of (my) Pinry use-case.

I'd say this would be very nice use-case as an optional plug-in, ideally.
But it also seems like a smallish patch (and we don't have a plug-in system currently), so… yeah, don't have strong opinions about it.

PS: I'd suggest to "squash out" the copyrighted-font commit out of the PR and possibly rebasing to latest trunk (mostly to avoid the Docker-related changes in the patch).

**Comment by winkidney** [comment]
@lapo-luchini Thanks for you opinion, it make sense that we should make this as plugin.
I'll try to made a plugin system after I made a sqush commit of this feature. @Rousong

**Comment by winkidney** [comment]
Feel sorry but the new free font is not really "free", some information from the web:

> If you'd like to embed this font in an app, ebook, on the web or anything that's not covered by the desktop license agreement, visit the link below. You'll find distributors who offer different types of licenses or you can contact me for help.
> 
> https://typodermicfonts.com/good-times/
> 
> This free font is part of a larger font family. Check out the rest of the family through the link above.

form:  https://www.dafont.com/good-times.font

**Comment by winkidney** [comment]
@Rousong source-han-sans is free for all use case：https://github.com/adobe-fonts/source-han-sans/blob/master/README-CN.md

**Comment by Rousong** [comment]
> @Rousong source-han-sans is free for all use case：https://github.com/adobe-fonts/source-han-sans/blob/master/README-CN.md

You are right, thanks.
I'd like to commit this font.

**Comment by winkidney** [comment]
I have made a simple plugin system to allow users to add watermark system to Pinry.
The link: https://github.com/pinry/pinry/pull/194

Thanks for your great work on watermark making but I'm afraid I coundn't agree to merge your pull request to Pinry's master.

But you could always create a standalone plugin project for Pinry, just like: https://github.com/winkidney/pinry_watermark

This is code from you and reformatted by our new plugin system.

Your PR's feature is nice, but it merges much meaningless codes from our master.

You should use rebase or simple not merge our master to your own branch.

And, I've remove an "print" in your code(this is just a small bug, haha).

**Comment by lapo-luchini** [comment]
Wow @winkidney, that was fast! =)

**Comment by Rousong** [comment]
I think it's a wonderful feature to add a plugin system.
Thanks for your work! 
@winkidney

**Comment by winkidney** [comment]
@Rousong We may add a plugin page which includes a link to your watermark plugin.
Once you done the refactor-work on plugin, feel free to send me a message.

**Pull request closed without merging**
